--Primarias
ALTER TABLE FISICOS ADD CONSTRAINTS PK_Fisicos
    PRIMARY KEY(Videojuego);

ALTER TABLE DIGITALES ADD CONSTRAINTS PK_Digitales
    PRIMARY KEY(Videojuego);

ALTER TABLE  DLCS ADD CONSTRAINTS PK_DLCs
    PRIMARY KEY(D_id);

ALTER TABLE PLATAFORMAS ADD CONSTRAINTS PK_Plataformas
    PRIMARY KEY(P_id);

ALTER TABLE VIDEOJUEGOS ADD CONSTRAINTS PK_Videojuegos
    PRIMARY KEY(V_id);

ALTER TABLE VIDEOJUEGOSPORCATEGORIAS ADD CONSTRAINTS PK_VideojuegosPorCategoria
    PRIMARY KEY(Categoria, Videojuego);

ALTER TABLE CATEGORIAS ADD CONSTRAINTS PK_Categorias
    PRIMARY KEY(C_id);

ALTER TABLE RECOMIENDAN ADD CONSTRAINTS PK_Recomiendan
    PRIMARY KEY(Usuario, Videojuego);

ALTER TABLE USUARIOS ADD CONSTRAINTS PK_Usuarios
    PRIMARY KEY(U_id);

ALTER TABLE CARRITOSCOMPRAS ADD CONSTRAINTS PK_CarritoCompras
    PRIMARY KEY(CC_id);

ALTER TABLE ENVIOS ADD CONSTRAINTS PK_Envios
    PRIMARY KEY(E_id);

--Unicas

ALTER TABLE DLCS ADD CONSTRAINTS UK_DLCs
    UNIQUE(nombre, p_url, trailer);

ALTER TABLE VIDEOJUEGOS ADD CONSTRAINTS UK_Videojuegos
    UNIQUE(p_url, trailer);

ALTER TABLE USUARIOS ADD CONSTRAINTS UK_Usuarios
    UNIQUE(nickName, correo, direccion);

--Foraneas

ALTER TABLE FISICOS ADD CONSTRAINTS FK_Fisicos_Videojuegos
    FOREIGN KEY(Videojuego) REFERENCES VIDEOJUEGOS(V_id);

ALTER TABLE DIGITALES ADD CONSTRAINTS FK_Digitales_Videojuegos
    FOREIGN KEY(Videojuego) REFERENCES VIDEOJUEGOS(V_id);

ALTER TABLE DLCS ADD CONSTRAINTS FK_DLCs_Videojuegos
    FOREIGN KEY(Videojuego) REFERENCES VIDEOJUEGOS(V_id);

ALTER TABLE VIDEOJUEGOS ADD CONSTRAINTS FK_Videojuegos_Plataformas
    FOREIGN KEY(Plataforma) REFERENCES PLATAFORMAS(P_id);

ALTER TABLE VIDEOJUEGOS ADD CONSTRAINTS FK_Videojuegos_CarritosCompras
    FOREIGN KEY(CarritoCompra) REFERENCES CARRITOSCOMPRAS(CC_id);

ALTER TABLE VIDEOJUEGOSPORCATEGORIAS ADD CONSTRAINTS FK_VideojuegosPorCategoria_Videojuegos
    FOREIGN KEY(Videojuego) REFERENCES VIDEOJUEGOS(V_id);

ALTER TABLE VIDEOJUEGOSPORCATEGORIAS ADD CONSTRAINTS FK_VideojuegosPorCategoria_Categorias
    FOREIGN KEY(Categoria) REFERENCES CATEGORIAS(C_id);

ALTER TABLE RECOMIENDAN ADD CONSTRAINTS FK_Recomiendan_Usuario
    FOREIGN KEY(Usuario) REFERENCES USUARIOS(U_id);

ALTER TABLE RECOMIENDAN ADD CONSTRAINTS FK_Recomiendan_Videojuegos
    FOREIGN KEY(Videojuego) REFERENCES VIDEOJUEGOS(V_id);

ALTER TABLE USUARIOS ADD CONSTRAINTS FK_Usuarios_CarritosCompras
    FOREIGN KEY(CarritoCompra) REFERENCES CARRITOSCOMPRAS(CC_id);

ALTER TABLE USUARIOS ADD CONSTRAINTS FK_Usuarios_Videojuegos
    FOREIGN KEY(Videojuego) REFERENCES Videojuegos(V_id);

ALTER TABLE ENVIOS ADD CONSTRAINTS FK_Envios_CarritosCompras
    FOREIGN KEY(CarritoCompra) REFERENCES CARRITOSCOMPRAS(CC_id);

--Atributos

ALTER TABLE VIDEOJUEGOS
ADD CONSTRAINT CK_Videojuegos_precio CHECK(precio > 0);

ALTER TABLE USUARIOS
ADD CONSTRAINT CK_Usuarios_hR CHECK(horasRegistradas > 0);

ALTER TABLE CARRITOSCOMPRAS
ADD CONSTRAINT CK_Facturaciones_TPAGO CHECK(metodoPago IN ('D','C'));

ALTER TABLE DLCS
ADD CONSTRAINT CK_DLCs_precio CHECK(precio > 0);

ALTER TABLE VIDEOJUEGOS
ADD CONSTRAINT CK_Videojuegos_T_imagen_trailer_etiqueta CHECK(imagenes IN ('P','S','J') AND trailer IN ('M','A') AND etiqueta IN ('E','E10','T','M','AO'));

ALTER TABLE FISICOS
ADD CONSTRAINT CK_Fisicos_TempaqueTstock CHECK(tipoEmpaque IN ('D','C') AND stock IN ('S','N'));

ALTER TABLE DLCS
ADD CONSTRAINT CK_DLCs_T_imagen_video_etiqueta CHECK(imagen IN ('P','S','J') AND trailer IN ('M','A') AND etiqueta IN ('E','E10','T','M','AO'));


ALTER TABLE CARRITOSCOMPRAS
ADD CONSTRAINT CK_CarritoCompras_subTotal_ttoal_pV_dP CHECK(subTotal > 0 AND precioVideojuego > 0 AND DLCPrecio > 0 AND total > 0);
